[workspace]

members = [
    "detours-sys",
    "level_zero-sys",
    "level_zero",
    "spirv_tools-sys",
    "zluda",
    "zluda_dump",
    "zluda_lib",
    "zluda_inject",
    "zluda_redirect",
    "ptx",
]

default-members = ["zluda_lib", "zluda_inject", "zluda_redirect"]

[patch.crates-io]
rspirv = { git = 'https://github.com/vosen/rspirv', rev = '40f5aa4dedb0d9f1ec24bdd8b6019e01996d1d74' }
spirv_headers = { git = 'https://github.com/vosen/rspirv', rev = '40f5aa4dedb0d9f1ec24bdd8b6019e01996d1d74' }